apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-oidc-client

spec:
  # Refresh the token at regular intervals
  refreshInterval: 1m

  # Fetch secret from the application's default secret store
  secretStoreRef:
    kind: SecretStore
    name: argocd-secret-store

  target:
    name: argocd-oidc-client

    # this is how the Kind=Secret will look like
    template:
      engineVersion: v2

      data:
        clientId: "{{ .argocd_oidc_client_id }}"
        clientSecret: "{{ .argocd_oidc_client_secret }}"

  data:
    # Fetch OIDC client ID/secret  from the default secret store and make it available to templating engine
    - secretKey: argocd_oidc_client_id
      remoteRef:
        key: argocd-oidc-client-id

    - secretKey: argocd_oidc_client_secret
      remoteRef:
        key: argocd-oidc-client-secret
