# This manages the ArgoCD configuration itself

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argocd
spec:
  # Deploy the application to specified cluster/namespace
  destination:
    name: talos-default
    namespace: argocd

  # Fetch resources for the Application from this Git repo
  source:
    path: core-services/self-managed/argo-cd/overlays/local
    repoURL: https://github.com/kalmalyzer/managed-cluster.git
