apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

  # Allow other programs to create ExternalSecrets that reference the
  # 'local-secret-store' ClusterSecretStore within the 'local-secret-store' namespace
  - local-secret-store

patches:
  - path: argo-cd-application.patch.yaml
  - path: argocd-project.patch.yaml
