apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  destination:
    name: talos-default
    namespace: argocd

  source:
    path: apps/cert-manager
    repoURL: https://github.com/kalmalyzer/managed-cluster.git
