apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cert-manager-namespace.yaml

# Do not force all resources into the cert-manager namespace; cert-manager wants to install a few Roles into kube-system as well
# namespace: cert-manager

helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    releaseName: cert-manager
    namespace: cert-manager
    version: 1.16.1
    includeCRDs: true
    additionalValuesFiles:
      - values/install-crds.yaml
