apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  destination:
    name: gke
    namespace: cert-manager

  source:
    path: apps/cert-manager/k8s
    repoURL: https://github.com/kalmalyzer/managed-cluster.git
