apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  source:
    path: apps/external-secrets/k8s/overlays/gke
    repoURL: https://github.com/kalmalyzer/managed-cluster.git
