apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  destination:
    name: gke
    namespace: external-secrets

  source:
    path: apps/external-secrets/overlays/gke
    repoURL: https://github.com/kalmalyzer/managed-cluster.git
