apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  destination:
    name: talos-default
    namespace: monitoring

  source:
    path: apps/kube-prometheus-stack
    repoURL: https://github.com/kalmalyzer/managed-cluster.git
