# This Application ensures that all Applications within /apps/applications get created

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/name: argocd-applications
  name: argocd-applications
  namespace: argocd
spec:
  # OVERRIDE PER-ENVIRONMENT
  destination:
    name: <cluster name>
    namespace: argocd
  ignoreDifferences:
    - group: argoproj.io
      jsonPointers:
        - /status
      kind: Application
  project: application-generators
  # OVERRIDE PER-ENVIRONMENT
  source:
    path: <apps-config/applications folder for this environment>
    repoURL: <Git repository URL>
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - allowEmpty=true
