# Declare a health check for the argocd-server service
# The GKE HTTPS Load Balancer will use this health check to determine whether or not the argocd-server service is up and running

apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: argocd-server
spec:
  default:
    checkIntervalSec: 30
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 2
    logConfig:
      enabled: true
    config:
      type: HTTP
      httpHealthCheck:
        requestPath: /healthz
        # Even though we reference a Service, the health check requests will be sent directly to the Pods
        # Therefore, we specify the relevant port number on the Pods rather than the Service's port number
        port: 8080
  targetRef:
    group: ""
    kind: Service
    name: argocd-server
