# This manages the ArgoCD configuration itself

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: argo-cd
  name: argo-cd
  namespace: argocd
spec:
  # OVERRIDE PER-ENVIRONMENT
  # Deploy the application to specified cluster/namespace
  destination:
    name: <cluster name>
    namespace: argocd

  # Ignore these differences between live and desired states during the diff. Note that these configurations are not
  # used during the sync process unless the `RespectIgnoreDifferences=true` sync option is enabled.
  ignoreDifferences:
    - group: argoproj.io
      jsonPointers:
        - /status
      kind: Application

  # The Project which this Application belongs to
  project: argocd

  # OVERRIDE PER-ENVIRONMENT
  # Fetch resources for the Application from this Git repo
  source:
    path: core-services/self-managed/argo-cd/overlays/<environment folder name>
    repoURL: <Git repository URL>

  syncPolicy:
    automated:
      # Allow automated sync to delete resources, if thre are resources in the cluster but the Git repo is completely empty
      # Reference: https://argo-cd.readthedocs.io/en/stable/user-guide/auto_sync/#automatic-pruning-with-allow-empty-v18
      allowEmpty: true

      # Allow automated sync to delete resources, if they exist in the cluster but not in the Git repo
      # Reference: https://argo-cd.readthedocs.io/en/stable/user-guide/auto_sync/#automatic-pruning
      prune: true

      # Allow automated syncs to be triggered by changes to the live cluster (this makes the application self-healing)
      # Reference: https://argo-cd.readthedocs.io/en/stable/user-guide/auto_sync/#automatic-self-healing
      selfHeal: true
