apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:

  # Bind external-secrets K8s Service Account to corresponding GCP Service Account
  - path: use-workload-identity-for-external-secrets.yaml
