# This account is bound to a corresponding Google Service Account via Workload Identity
#   and this enables External Secrets Operator to interact with GCP resources

apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  annotations:
    iam.gke.io/gcp-service-account: external-secrets@kalmalyzer-external-secrets.iam.gserviceaccount.com
