# This Application ensures that all Applications within /apps/applications get created

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-applications
  namespace: argocd
spec:
  source:
    path: apps-config/applications/k8s/overlays/gke
    repoURL: https://github.com/kalmalyzer/managed-cluster.git
