apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  destination:
    name: talos-default
    namespace: argocd

  source:
    path: apps/argocd/k8s/overlays/local
    repoURL: https://github.com/kalmalyzer/managed-cluster.git
