apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-secrets

resources:
  # Create 'external-secrets' namespace
  - external-secrets-namespace.yaml

  # Install External Secrets Operator, including CRDs
  - application
