# This account is bound to a corresponding Google Service Account via Workload Identity
#   and this enables argocd-application-controller to interact with GCP resources

apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-application-controller
  annotations:
    iam.gke.io/gcp-service-account: argocd-application-controller@kalms-argocd.iam.gserviceaccount.com
