# This Application ensures that all AppProjects within /apps/projects get created

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-projects
  namespace: argocd
spec:
  destination:
    name: gke
    namespace: argocd
  source:
    path: apps-config/projects/overlay/gke
    repoURL: https://github.com/kalmalyzer/managed-cluster.git
