apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: traefik
    repo: https://traefik.github.io/charts
    releaseName: traefik
    version: latest
    includeCRDs: true
    additionalValuesFiles:
      - values.yaml
