# Project for external-secrets

apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: external-secrets
  namespace: argocd
spec:
  description: external-secrets project

  # OVERRIDE PER-ENVIRONMENT
  sourceRepos:
    # Only allow fetching configuration from the primary Git repo
    - <Git repository URL>

  destinations:
    # Only allow deploying to the 'external-secrets' namespace within the cluster
    - name: in-cluster
      namespace: external-secrets
    # ... plus, a few Roles & RoleBindings go into the 'kube-system' namespace
    - name: in-cluster
      namespace: kube-system

  # Provide a shortlist of cluster-scope resources that are allowed; by default, none are allowed
  clusterResourceWhitelist:
    - group: "*"
      kind: Namespace
    - group: "*"
      kind: CustomResourceDefinition
    - group: "*"
      kind: ClusterRole
    - group: "*"
      kind: ClusterRoleBinding
    - group: "*"
      kind: ValidatingWebhookConfiguration
