# Reference: https://external-secrets.io/latest/provider/kubernetes/#authentication
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: local-secret-store
  name: local-secret-store-cluster-role
rules:
- apiGroups: [""]
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - authorization.k8s.io
  resources:
  - selfsubjectrulesreviews
  verbs:
  - create
