# This introduces a Project that is intended to contain global configuration that applies to all other Projects

apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: global-project
  namespace: argocd
spec:
  description: Global project

  syncWindows:
  - kind: deny
    schedule: "* * * * *"
    timeZone: "Europe/Amsterdam"
    duration: "1h"
    applications:
    - "*"
    manualSync: true
