apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-github-webhook-secret

spec:
  # Refresh the token at regular intervals
  refreshInterval: 1m

  # Fetch secret from the application's default secret store
  secretStoreRef:
    kind: SecretStore
    name: argocd-secret-store

  target:
    # ArgoCD has all key-value pairs within a single secret
    # The ArgoCD deployment controls the existence of the secret itself
    name: argocd-secret

    # When adding/modifying the external secret key-value pair, expect the K8s secret to already exist, and update fields in it
    creationPolicy: Merge
    # When removing the external secret key-value pair, remove fields from the K8s secret, but leave the remainder of the K8s secret as-is
    deletionPolicy: Merge

  data:
    # Set key-value pair within secret with the contents of secret store's secret
    - secretKey: webhook.github.secret
      remoteRef:
        key: argocd-github-webhook-secret
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
