apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-secrets

resources:
  # Create 'external-secrets' namespace
  - external-secrets-namespace.yaml

  # Install External Secrets Operator, including CRDs
  - https://github.com/external-secrets/external-secrets/releases/download/v0.10.0/external-secrets.yaml

patches:
  # Update namespace for cert-controller
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/args/3
        value: "--service-namespace=external-secrets"
      - op: replace
        path: /spec/template/spec/containers/0/args/5
        value: "--secret-namespace=external-secrets"
    target:
      kind: Deployment
      name: external-secrets-cert-controller

  # Update namespace for webhook
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/args/2
        value: "--dns-name=external-secrets-webhook.external-secrets.svc"
    target:
      kind: Deployment
      name: external-secrets-webhook
